# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "fancy"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "fancy"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				bee = true
				axolotl = true
				egg = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				bat = true
				husk = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				turtle = true
				shulker = true
				wandering_trader = true
				salmon = true
				wither_skeleton = true
				piglin_brute = true
				ocelot = true
				item_frame = true
				horse = true
				minecart = true
				ender_dragon = true
				leash_knot = true
				spectral_arrow = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				tnt = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				chicken = true
				ravager = true
				trader_llama = true
				donkey = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				iron_golem = true
				zombified_piglin = true
				piglin = true
				cat = true
				zombie = true
				ender_pearl = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				wolf = true
				villager = true
				skeleton_horse = true
				zombie_villager = true
				boat = true
				strider = true
				witch = true
				cod = true
				spider = true

