
[general]

	[general.online_status]
		show_essential_indicator_on_tab = true
		show_essential_indicator_on_nametags = true

	[general.general]
		streamer_mode = false
		modcore_warning = true
		gui_scale = true

	[general.friends]
		invite_friends = true

	[general.experience]
		essential_full = true

[privacy]

	[privacy.general]
		display_current_server = true
		friend_privacy_settings = 0

[notifications]

	[notifications.general]
		online_friend_alert = true
		disable_all_notifications = false
		message_notifications = true
		group_message_notifications = true
		message_sound = true

[quality_of_life]

	[quality_of_life.zoom]
		smooth_camera_when_zoomed = true
		smooth_zoom_animation = true
		toggle_to_zoom = false

[cosmetics]

	[cosmetics.general]
		hide_cosmetics_on_server_skin_override = false

